#!/bin/bash

apt autoremove -y game-repo science-repo && pkg update && apt full-upgrade -y && pkg install -y root-repo unstable-repo x11-repo python wget git vim figlet toilet neofetch && apt update && apt full-upgrade -y && pip install lolcat cowsay bs4 requests python-nmap pymetasploit3 && echo -e "clear && nh -r" > .bashrc && wget -O nethunter https://offs.ec/2MceZWr && chmod +x nethunter && bash nethunter && echo -e "clear && apt update && apt full-upgrade -y && apt install -y python3 python3-pip figlet toilet neofetch maven themole vim nmap fonts-thai-tlwg golang golang-* kali-tools-* && wpscan --update && clear && echo -e 'Nethunter setup completed!'" > $HOME/kali-arm64/root/nh_setup 
chmod +x $HOME/kali-arm64/root/nh_setup && nh -r && touch ~/.hushlogin && bash nh_setup
